services:
  sync-app:
    build: .
    container_name: sync-app-711k
    restart: always
    ports:
      - "3600:3600"
    environment:
      - REDIS_HOST=sync-redis
      - REDIS_PORT=6379
      - NODE_ENV=production
      - SAE_TOKEN=${SAE_TOKEN}
      - SAE_CONNECT=${SAE_CONNECT}
      - SAE_AUTH=${SAE_AUTH}
      - SAE_COOKIE=${SAE_COOKIE}
      - XUI_DB_HOST=${XUI_DB_HOST}
      - XUI_DB_PORT=${XUI_DB_PORT}
      - XUI_DB_USER=${XUI_DB_USER}
      - XUI_DB_PASS=${XUI_DB_PASS}
      - XUI_DB_NAME=${XUI_DB_NAME}
      - XUI_HOST=${XUI_HOST}
      - XUI_API_KEY=${XUI_API_KEY}
    depends_on:
      - sync-redis


  sync-redis:
    image: redis:7-alpine
    container_name: sync-redis-queue
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  migration_high_performance.cql:
